#!/bin/bash

# Put your device here. You can get it by running 'ip link' or
# 'ls /sys/class/net' in a terminal.
#DEVICE=enp63s0
#DEVICE=ens3
DEVICE=eth0
#DEVICE=wlp12s0
#DEVICE=wlan0

IPLIST=/var/cache/ban404/ip.lst

[[ "$1" = "install" ]] && {
	[[ $UID -eq 0 ]] || { echo "ban404 error: Must be run as root"; exit 1; }

	mkdir -pv $(dirname "$IPLIST")
	touch "$IPLIST"
	cp -v ban404 /usr/sbin
	cp -v ban404.service /usr/lib/systemd/system
	systemctl daemon-reload
	systemctl start ban404

	exit 0
}

# run as a daemon
[ "$1" = "-d" ] && {
	[[ -d /var/log/apache2 ]] && LOGDIR=/var/log/apache2 || {
		[[ -d /var/log/httpd ]] && LOGDIR=/var/log/httpd
	}
	[[ -z "$LOGDIR" ]] && { echo "ban error: Cannot find /var/log/apache2 or /var/log/httpd"; exit 1; }

	[[ -e "$LOGDIR/access_log" ]] && LOGFILE=$LOGDIR/access_log || {
		[[ -e "$LOGDIR/access.log" ]] && LOGFILE=$LOGDIR/access.log
	}
	[[ -z "$LOGFILE" ]] && { echo "ban error: Cannot find $LOGDIR/access_log or $LOGDIR/access.log"; exit 1; }

	$0 -a
	CNT=0
	MIN=$(date +%M)
	MINPREV=$MIN
	IP=1.1.1.1
	IPPREV=$IP
	tail -n15 -f $LOGFILE | while read LINE; do
		IP=$(echo "$LINE" | awk '{ print $1 }')
		if [ "$IP" = "$IPPREV" ]; then
			MIN=$(echo "$LINE" | awk -F: '{ print $3 }')
			CMD=$(echo "$LINE" | awk '{ print $6 }')
			if [ $MIN -eq $MINPREV ]; then
				if [ "$CMD" = "\"GET" -o "$CMD" = "\"POST" -o "$CMD" = "\"CONNECT" ]; then
					STATUS=$(echo "$LINE" | awk '{ print $9 }')
					[ $STATUS -eq 404 -o $STATUS -eq 405 ] && ((++CNT))
				elif [ "$CMD" = "\"-\"" ]; then
					((++CNT))
				fi
			else
				MINPREV=$MIN
				CNT=0
			fi
			[ $CNT -ge 9 ] && {
				$0 "$IP"
				CNT=0
			}
		else
			IPPREV=$IP
			CNT=0
		fi
	done
	exit 0
}

[ "$1" = "-a" ] && {
	iptables -F
	# iptables -A INPUT -p icmp -j LOG --log-prefix "ping "
	for ip in `cat $IPLIST`; do
		iptables -A INPUT -i $DEVICE -s $ip -j DROP
	done
}

if [ "$(basename $0)" = "unban" ]; then
	echo "$1" | grep -E "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" >/dev/null && {
		grep "$1" $IPLIST >/dev/null && {
			iptables -D INPUT -i $DEVICE -s $1 -j DROP &&
				sed -i "/$1/d" $IPLIST
		}
	}
	exit 0
else # ban
	echo "$1" | grep -E "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" >/dev/null && {
			iptables -A INPUT -i $DEVICE -s $1 -j DROP &&
				echo "$1" >> $IPLIST
	}
fi

